### ISSUE TITLE
thread safety

### ISSUE THREAD

**Issue by MrAliSalehi** [ZesaHG/ProcMem#1]
Hi there, thank you for creating this!

Im trying to pass an instance of `Process` to different threads, I implemented Send & Sync for Process in my own fork, but now when i Run the program at `--release` mode, I get `(exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)` at the line that im Cloning the Process Arc,

```rust
let proc = Arc::new(Process::with_name("name").unwrap());

let a_p = Arc::clone(&proc);
    std::thread::spawn(move || {
        let proc = Arc::clone(&a_p);
        loop {
          //....
        }
    });

 let b_p = Arc::clone(&proc); // fails exactly here
    std::thread::spawn(move || {

        let p = Arc::clone(&b_p );
        loop {
//....
        }
    });

```

is there any way that Process could actually be thread safe?

**Comment by ZesaHG** [comment]
Hello @MrAliSalehi,

I have tried to replicate your issue, but unfortunately to no avail.
Basically doing the same as you:

``` rust
let testproc = Arc::new(Process::with_name("SomeGamesLauncher.exe").unwrap());
let proc_clone1 = Arc::clone(&testproc);
let proc_clone2 = Arc::clone(&testproc);

std::thread::spawn(move || {
    let proc1 = Arc::clone(&proc_clone1);
    println!("Clone1 Process ID: {}", proc1.process_id);
});

std::thread::spawn(move || {
    let proc2 = Arc::clone(&proc_clone2);
    println!("Clone2 Process ID: {}", proc2.process_id);
});
```

build in --release (nightly-x86_64-pc-windows-msvc)
ran the .exe and got as result:
```
Clone2 Process ID: 18376
Clone1 Process ID: 18376
```

Regarding the threadsafety, you should not have any issues since you are not modifying struct members of "Process" or "Module".


Best regards,
Zesa.

**Comment by MrAliSalehi** [comment]
could you please try to read memory from that process in differenct threads?
im getting some really weird behaviors, for example im reading a memory ptr which for example returns a pointer : xx, when I use this pointer in another thread, the value becomes zero! but in the same thread it works fine, or when the buffer for read_ptr is `i32` it returns the value but when its `usize` it returns zero again, lol

**Comment by MrAliSalehi** [comment]
its strange that i can read a value in normal run, but it fails to read it with release mode

```rust

let proc = Arc::new(Process::with_name("game.exe").unwrap());

let client = proc.module("dll");
let base = client.base_address();

// correct both on debug and release 
println!("base: {},n: {}", base, client.name()); 


let mut data1 = 0; 
let mut data2= 0;

proc.read_ptr(&mut data1, base + some_offset, 8);
proc.read_ptr(&mut data2, data1+ offset, 8);
println!("entityList {}, entry: {}", data1, data2);  // zero at release mode, but it works fine at debug mode

```

**Comment by ZesaHG** [comment]
> for example im reading a memory ptr which for example returns a pointer : xx, when I use this pointer in another thread, the value becomes zero

Like do you have a pointer which you read with "read_ptr" or do you try to dereference it or how do you use this?
Could you please give some example code to that issue?
If you can provide that, I will have a look into that issue.
 
> when the buffer for read_ptr is i32 it returns the value but when its usize it returns zero again

Well I guess you are coding a 64bit application so they have different sizes (i32 -> 4 Bytes | usize -> 8Bytes)

Another thing with your code I noticed is this part:
```rust
    let mut data1 = 0; 
    let mut data2 = 0;
    proc.read_ptr(&mut data1, base + some_offset, 8);
    proc.read_ptr(&mut data2, data1+ offset, 8);
```

The third parameter to "read_ptr" is basically just for reading multiple bytes e.g.: u8 since its multiplying the size of "T" with "count"(aka. third parameter).
So in order to read like i32 you just pass "1".
```rust
    let mut value_buffer: i32 = 0;
    proc.read_ptr(&mut value_buffer, addr_to_read, 1);
```

With passing "8" as you do, you basically provide this as the size to read:
```rust
    std::mem::size_of::<i32>() as SIZE_T * 8
```

Based of of your code snippet, you could just use the "read_mem" method:
```rust
    let data: i32 = proc.read_mem(addr);
```
